export const categories = [
  { name: "Programming & Tech", slug: "programming-tech" },
  { name: "Graphics & Design", slug: "graphics-design" },
  { name: "Digital Marketing", slug: "digital-marketing" },
  { name: "Video & Animation", slug: "video-animation" },
  { name: "Writing & Translation", slug: "writing-translation" },
  { name: "Music & Audio", slug: "music-audio" },
  { name: "Business & Entrepreneurship", slug: "business" },
  { name: "Finance & Accounting", slug: "finance" },
  { name: "AI Services", slug: "ai-services" },
  { name: "Lifestyle & Wellness", slug: "lifestyle" },
  { name: "Consulting", slug: "consulting" },
  { name: "Data Science & Analytics", slug: "data-science" },
  { name: "Health & Fitness", slug: "health-fitness" },
  { name: "Others", slug: "others" },
];
